# Generated by Django 6.0.5 on 2026-05-15 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
