# Generated by Django 6.0.5 on 2026-05-12 20:26

import events.validators.event_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, validators=[events.validators.event_validators.validate_name_length]),
        ),
    ]
