# Generated by Django 6.0.5 on 2026-06-15 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-start_date'], name='event_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'price'], name='ticket_event_price_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['available_seats'], name='ticket_avail_seats_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_per_event'),
        ),
    ]
