# Generated by Django 6.0.5 on 2026-06-15 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_tickettype_options_event_event_status_date_idx_and_more'),
        ('reviews', '0004_review_unique_review_per_user_per_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-rating'], name='review_user_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event', '-rating'], name='review_event_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event', '-created_at'], name='review_event_date_idx'),
        ),
    ]
