# Generated by Django 6.0.5 on 2026-06-15 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_waitlistentry_alter_booking_status_and_more'),
        ('events', '0005_alter_tickettype_options_event_event_status_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-booked_at'], name='booking_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ticket_type', 'status'], name='booking_ticket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['ticket_type', 'is_active', 'position'], name='waitlist_core_idx'),
        ),
    ]
